texts = {
    "English": {
        "settings": "Settings",
        "api_label": "Your API",
        "notifications_label": "Notifications",
        "language_label": "Application language",
        "appearance_mode_label": "Appearance mode",
        "save_button": "Save",
        "version_label": "Version 1.0.0",
        "home_button": "Home",
        "history_button": "History",
        "settings_button": "Settings",
        "success_message_description": "Settings saved successfully. Restart program",
        "success_message_topic" : "Success",
        "home" : "Dear Home",
        "import_button" : "Import",
        "export_button" : "Export",
        "radio_button_1" : "Online",
        "radio_button_2" : "Offline",
        "start_subtitles_button" : "Run",
        "import_label" : "Import:  ",
        "export_label" : "Export:  ",
        "status_label" : "Status:  ",
        "status_progress_label_working" : "Working",
        "status_progress_label_done" : "Done",
        "error_topic" : "Erorr",
        "api_error_description" : "Authentication error, API token missing/invalid",
        "error_path_to_files" : "Please choose import and export",
        "error_radio_button" : "Please choose mode Online/Offline",
        "save_subtitles_error" : "Change folder in export",
        "status_progress_preparing" : "Preparing for subtitles generation",
        "history" : "History",
        "file_input_label" : "File",
        "mode_label" : "Mode",
        "start_time_lable" : "Date",
        "total_time_label" : "Total time",
        "notification_title" : "Success",
        "notification_description" : "Your subtitles are ready"
    },
    "Ukrainian": {
        "settings": "Налаштування",
        "api_label": "Ваш API",
        "notifications_label": "Сповіщення",
        "language_label": "Мова застосунку",
        "appearance_mode_label": "Режим вигляду",
        "save_button": "Зберегти зміни",
        "version_label": "Версія 1.0.0",
        "home_button": "Головна",
        "history_button": "Історія",
        "settings_button": "Налаштування",
        "success_message_description": "Налаштування збережено успішно. Перезавантажти програму",
        "success_message_topic" : "Успіх",
        "home" : "Головна",
        "import_button" : "Імпортувати",
        "export_button" : "Експортувати",
        "radio_button_1" : "Онлайн",
        "radio_button_2" : "Офлайн",
        "start_subtitles_button" : "Запустити",
        "import_label" : "Імпорт:  ",
        "export_label" : "Експорт:  ",
        "status_label" : "Статус:  ",
        "status_progress_label_working" : "Працює",
        "status_progress_label_done" : "Готово",
        "error_topic" : "Помилка",
        "api_error_description" : "Помилка автентифікації, токен API відсутній/недійсний",
        "error_path_to_files" : "Будь ласка, оберіть імпорт та експорт",
        "error_radio_button" : "Будь ласка, оберіть режим Онлайн/Офлайн",
        "save_subtitles_error" : "Виберіть іншу папку в експорті",
        "status_progress_preparing" : "Готуємо ваш файл до генерації субтитрів",
        "history" : "Історія",
        "file_input_label" : "Файл",
        "mode_label" : "Режим",
        "start_time_lable" : "Дата",
        "total_time_label" : "Загальний час",
        "notification_title" : "Успіх",
        "notification_description" : "Ваші субтитри готові"
    }
}